version: '2'

services:
    reverseproxy:
        image: reverseproxy
        ports:
            - 80:80
        restart: always

    farmer:
        depends_on:
            - reverseproxy
        ports:
            - 8080:8080
        image: kaarebs/farmer:latest
        restart: always